### ISSUE TITLE
Merge from CW's upstream updates, if no conflict.

### ISSUE THREAD

**Issue by tlkahn** [archway-network/wasmd#22]
### Pipeline/security
- Can we merge with CW's upstream updates? CW's wasmd is now [0.27](https://medium.com/cosmwasm/wasmd-0-27-released-57cc7dd754a6). 
- We should also have setups to create PRs to merge with major dep updates.
- Maybe we should consider using dependabot or similar tools.

**Comment by santanaluiz** [comment]
Invalid... closing
